// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2-6kO10YBpckLbNmh6S6amDO-h0Q0yo',
    appId: '1:41475249711:web:f8c851abe55fdc412c58da',
    messagingSenderId: '41475249711',
    projectId: 'talkative-5d7e0',
    authDomain: 'talkative-5d7e0.firebaseapp.com',
    storageBucket: 'talkative-5d7e0.appspot.com',
    measurementId: 'G-41MGPGR9EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOo9HPYZHXrpiAxfbrCKWTevFZpqI4KI',
    appId: '1:41475249711:android:84dde2d221f0f5502c58da',
    messagingSenderId: '41475249711',
    projectId: 'talkative-5d7e0',
    storageBucket: 'talkative-5d7e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FLzX0K4kPtWwbMJG6bu_-11jPxQBoJ4',
    appId: '1:41475249711:ios:f853d386d115b06e2c58da',
    messagingSenderId: '41475249711',
    projectId: 'talkative-5d7e0',
    storageBucket: 'talkative-5d7e0.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
